import React from "react";
import { 
  X, 
  Printer, 
  Download, 
  Sparkles, 
  CheckCircle, 
  Calendar, 
  Clock, 
  Award, 
  FileText, 
  ChevronRight,
  TrendingUp,
  Flame,
  Check,
  Briefcase
} from "lucide-react";
import { Task } from "../types";

interface ReportModalProps {
  tasks: Task[];
  onClose: () => void;
}

export default function ReportModal({ tasks, onClose }: ReportModalProps) {
  const dateStr = new Date().toLocaleDateString("en-US", {
    weekday: "long",
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const completedTasks = tasks.filter((t) => t.status === "completed");
  const pendingTasks = tasks.filter((t) => t.status === "todo");
  const completedCount = completedTasks.length;
  const totalCount = tasks.length;
  const completionPercentage = totalCount > 0 ? Math.round((completedCount / totalCount) * 100) : 0;

  // Calculate focus times
  const totalDuration = tasks.reduce((acc, t) => acc + (t.predictedTimeMinutes || t.duration || 0), 0);
  const completedDuration = completedTasks.reduce((acc, t) => acc + (t.predictedTimeMinutes || t.duration || 0), 0);

  // High priority stats
  const highPriorityTasks = tasks.filter(t => t.priority === "high");
  const completedHighPriority = highPriorityTasks.filter(t => t.status === "completed");

  // Determine an AI executive performance score and note based on metrics
  const getExecutiveInsight = () => {
    if (totalCount === 0) {
      return {
        score: "N/A",
        badge: "Timeline Empty",
        color: "text-slate-400 bg-slate-50",
        summary: "No tasks are scheduled for today. Start by adding goals to generate a timeline report."
      };
    }
    if (completionPercentage === 100) {
      return {
        score: "100/100",
        badge: "Elite Precision",
        color: "text-emerald-700 bg-emerald-50 border-emerald-200",
        summary: "Flawless day! You conquered 100% of your schedule. Morning high-priority tasks and cognitive blocks were maintained with surgical precision. Exceptional efficiency!"
      };
    }
    if (completionPercentage >= 75) {
      return {
        score: "A- Grade",
        badge: "High Performer",
        color: "text-blue-700 bg-blue-50 border-blue-200",
        summary: "Fantastic progress today! You cleared your core milestones and protected your peak morning hours. The remaining items can be safely deferred to tomorrow's dynamic slot."
      };
    }
    if (completionPercentage >= 40) {
      return {
        score: "B Grade",
        badge: "Balanced Effort",
        color: "text-amber-700 bg-amber-50 border-amber-200",
        summary: "Steady performance. You completed key milestones, but some timeline slippage occurred. Keep focus blocks under 90 minutes to reduce late afternoon cognitive fatigue."
      };
    }
    return {
      score: "Focus Shield Needed",
      badge: "Restructuring Suggested",
      color: "text-rose-700 bg-rose-50 border-rose-200",
      summary: "Low completion rate. We suggest reducing daily commitments and setting reminders on high-priority tasks. Use the Memora Optimizer to block out distraction-free morning sprints."
    };
  };

  const insight = getExecutiveInsight();

  // 1. Download Markdown (.md) summary report
  const downloadMarkdown = () => {
    let md = `# Memora AI Daily Performance & Timeline Report\n`;
    md += `**Date:** ${dateStr}\n`;
    md += `**Generated by:** Memora AI Scheduling Workspace\n\n`;

    md += `## 📊 DAY SUMMARY & METRICS\n`;
    md += `- **Overall Task Completion:** ${completionPercentage}% (${completedCount}/${totalCount} Tasks)\n`;
    md += `- **Active Focus Energy:** ${completedDuration}m focus realized / ${totalDuration}m scheduled total\n`;
    md += `- **Critical Priorities Cleared:** ${completedHighPriority.length} of ${highPriorityTasks.length} high priority goals\n`;
    md += `- **Executive Performance Grade:** ${insight.score} (${insight.badge})\n\n`;

    md += `## 🧠 SCHEDULING INSIGHTS & STRATEGY\n`;
    md += `> ${insight.summary}\n\n`;

    md += `## 🏆 COMPLETED MILESTONES & ACHIEVEMENTS\n`;
    if (completedTasks.length === 0) {
      md += `*No milestones registered as completed yet today.*\n\n`;
    } else {
      completedTasks.forEach((t) => {
        md += `### ✅ ${t.title}\n`;
        md += `- **Category:** ${t.category} | **Complexity:** ${t.complexity} | **Priority:** ${(t.priority || "medium").toUpperCase()}\n`;
        md += `- **Timeline Block:** ${t.start} - ${t.end} (${t.predictedTimeMinutes || t.duration} mins)\n`;
        if (t.description) md += `- **Description:** ${t.description}\n`;
        if (t.optimizationNote) md += `- **ML sequence strategy:** ${t.optimizationNote}\n`;
        if (t.subtasks && t.subtasks.length > 0) {
          md += `- **Subtask Breakdown:**\n`;
          t.subtasks.forEach(s => {
            md += `  - [${s.completed ? "x" : " "}] ${s.text}\n`;
          });
        }
        md += `\n`;
      });
    }

    md += `## ⏳ REMAINING TIMELINE & NEXT UP\n`;
    if (pendingTasks.length === 0) {
      md += `*No remaining tasks scheduled for today. All milestones completed!*\n\n`;
    } else {
      pendingTasks.forEach((t) => {
        md += `### ▢ ${t.title} [${(t.priority || "medium").toUpperCase()}]\n`;
        md += `- **Category:** ${t.category} | **Timeline Block:** ${t.start} - ${t.end} (${t.predictedTimeMinutes || t.duration} mins)\n`;
        if (t.description) md += `- **Details:** ${t.description}\n`;
        if (t.subtasks && t.subtasks.length > 0) {
          md += `- **Planned Subtasks:**\n`;
          t.subtasks.forEach(s => {
            md += `  - [ ] ${s.text}\n`;
          });
        }
        md += `\n`;
      });
    }

    md += `\n*End of report. Plan smart, live better with Memora AI.*`;

    const blob = new Blob([md], { type: "text/markdown;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.setAttribute("download", `Memora_Daily_Report_${new Date().toISOString().split('T')[0]}.md`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  // 2. Download beautiful Standalone HTML Printable Report (.html)
  const downloadHTML = () => {
    let html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Memora AI - Daily Summary & Milestones</title>
  <style>
    body {
      font-family: system-ui, -apple-system, "Segoe UI", Roboto, sans-serif;
      color: #1e293b;
      line-height: 1.5;
      padding: 40px;
      max-width: 800px;
      margin: 0 auto;
      background: #fafafa;
    }
    .card {
      background: #ffffff;
      border: 1px solid #e2e8f0;
      border-radius: 12px;
      padding: 24px;
      margin-bottom: 24px;
      box-shadow: 0 1px 3px rgba(0,0,0,0.05);
    }
    h1 {
      font-size: 24px;
      font-weight: 800;
      color: #0f172a;
      margin-top: 0;
      margin-bottom: 8px;
    }
    h2 {
      font-size: 16px;
      text-transform: uppercase;
      letter-spacing: 0.05em;
      color: #64748b;
      border-bottom: 1px solid #f1f5f9;
      padding-bottom: 8px;
      margin-top: 24px;
      margin-bottom: 16px;
    }
    .badge {
      display: inline-block;
      padding: 2px 8px;
      font-size: 11px;
      font-weight: 700;
      border-radius: 9999px;
      text-transform: uppercase;
    }
    .badge-success { background: #dcfce7; color: #166534; }
    .badge-info { background: #dbeafe; color: #1e40af; }
    .badge-warning { background: #fef3c7; color: #92400e; }
    .badge-danger { background: #fee2e2; color: #991b1b; }
    
    .grid {
      display: grid;
      grid-template-columns: repeat(3, 1fr);
      gap: 16px;
      margin-bottom: 24px;
    }
    .grid-item {
      background: #f8fafc;
      border: 1px solid #f1f5f9;
      border-radius: 8px;
      padding: 16px;
      text-align: center;
    }
    .grid-num {
      font-size: 24px;
      font-weight: 700;
      color: #0f172a;
    }
    .task-item {
      border-left: 3px solid #cbd5e1;
      padding-left: 16px;
      margin-bottom: 16px;
    }
    .task-item.completed {
      border-left-color: #22c55e;
    }
    .task-item.high {
      border-left-color: #ef4444;
    }
    .task-title {
      font-weight: 700;
      font-size: 14px;
      margin-bottom: 4px;
    }
    .task-meta {
      font-size: 12px;
      color: #64748b;
      margin-bottom: 4px;
    }
    .subtasks {
      list-style: none;
      padding-left: 0;
      margin: 8px 0 0 0;
      font-size: 12px;
    }
    .subtask {
      display: flex;
      align-items: center;
      gap: 8px;
      color: #475569;
    }
    @media print {
      body { background: white; padding: 0; }
      .card { border: none; box-shadow: none; padding: 0; }
      .no-print { display: none !important; }
    }
  </style>
</head>
<body>
  <div class="card">
    <div style="display: flex; justify-content: space-between; align-items: start; border-bottom: 2px solid #e2e8f0; padding-bottom: 16px; margin-bottom: 24px;">
      <div>
        <h1>Memora AI Scheduling Report</h1>
        <div style="font-size: 13px; color: #64748b;">Generated on ${dateStr}</div>
      </div>
      <div style="text-align: right;">
        <span class="badge badge-info" style="font-size: 12px; padding: 6px 12px;">Grade: ${insight.score}</span>
      </div>
    </div>

    <div style="background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 16px; margin-bottom: 24px;">
      <h3 style="margin-top:0; margin-bottom:8px; font-size:14px; color:#1e293b;">🧠 Scheduling Insights & Analysis</h3>
      <p style="font-style: italic; margin:0; font-size:13px; color:#475569;">"${insight.summary}"</p>
    </div>

    <h2>📊 Performance Metrics</h2>
    <div class="grid">
      <div class="grid-item">
        <div style="font-size: 11px; text-transform: uppercase; color: #64748b;">Completion</div>
        <div class="grid-num" style="color: #166534;">${completionPercentage}%</div>
        <div style="font-size: 11px; color: #94a3b8;">${completedCount} / ${totalCount} Tasks</div>
      </div>
      <div class="grid-item">
        <div style="font-size: 11px; text-transform: uppercase; color: #64748b;">Realized Focus</div>
        <div class="grid-num" style="color: #1d4ed8;">${completedDuration}m</div>
        <div style="font-size: 11px; color: #94a3b8;">out of ${totalDuration}m scheduled</div>
      </div>
      <div class="grid-item">
        <div style="font-size: 11px; text-transform: uppercase; color: #64748b;">High Priorities</div>
        <div class="grid-num" style="color: #b91c1c;">${completedHighPriority.length} / ${highPriorityTasks.length}</div>
        <div style="font-size: 11px; color: #94a3b8;">goals completed</div>
      </div>
    </div>

    <h2>✅ Accomplished Milestones</h2>
    ${completedTasks.length === 0 ? '<p style="color: #94a3b8; font-style: italic; font-size: 13px;">No completed milestones recorded for today.</p>' : ''}
    ${completedTasks.map(t => `
      <div class="task-item completed">
        <div class="task-title" style="color: #166534;">[Completed] ${t.title}</div>
        <div class="task-meta">
          <strong>Category:</strong> ${t.category} | <strong>Block:</strong> ${t.start} - ${t.end} (${t.predictedTimeMinutes || t.duration}m) | <strong>Priority:</strong> ${(t.priority || "medium").toUpperCase()}
        </div>
        ${t.description ? `<p style="margin: 4px 0 0 0; font-size: 12px; color: #475569;">${t.description}</p>` : ''}
        ${t.subtasks && t.subtasks.length > 0 ? `
          <ul class="subtasks">
            ${t.subtasks.map(s => `
              <li class="subtask">
                <span style="color: #22c55e;">✔</span>
                <span style="text-decoration: ${s.completed ? 'line-through' : 'none'}; color: ${s.completed ? '#94a3b8' : '#334155'}">${s.text}</span>
              </li>
            `).join('')}
          </ul>
        ` : ''}
      </div>
    `).join('')}

    <h2>⏳ Upcoming & Remaining Schedule</h2>
    ${pendingTasks.length === 0 ? '<p style="color: #22c55e; font-style: italic; font-weight: 600; font-size: 13px;">All daily tasks completed! Exceptional efficiency.</p>' : ''}
    ${pendingTasks.map(t => `
      <div class="task-item ${t.priority === 'high' ? 'high' : ''}">
        <div class="task-title" style="color: ${t.priority === 'high' ? '#b91c1c' : '#1e293b'};">
          ${t.title} ${t.priority === 'high' ? '<span class="badge badge-danger" style="margin-left: 8px;">High Urgent</span>' : ''}
        </div>
        <div class="task-meta">
          <strong>Category:</strong> ${t.category} | <strong>Estimated Time Slot:</strong> ${t.start} - ${t.end} (${t.predictedTimeMinutes || t.duration}m)
        </div>
        ${t.description ? `<p style="margin: 4px 0 0 0; font-size: 12px; color: #475569;">${t.description}</p>` : ''}
        ${t.subtasks && t.subtasks.length > 0 ? `
          <ul class="subtasks">
            ${t.subtasks.map(s => `
              <li class="subtask">
                <span style="color: #94a3b8;">☐</span>
                <span style="color: #475569;">${s.text}</span>
              </li>
            `).join('')}
          </ul>
        ` : ''}
      </div>
    `).join('')}

    <div style="border-top: 1px solid #e2e8f0; margin-top: 40px; padding-top: 16px; text-align: center; font-size: 11px; color: #94a3b8;">
      Report compiled automatically by Memora AI Companion. Optimize timeline, eliminate fatigue, achieve your potential.
    </div>
  </div>
</body>
</html>`;

    const blob = new Blob([html], { type: "text/html;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.setAttribute("download", `Memora_Daily_Summary_${new Date().toISOString().split('T')[0]}.html`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  // 3. Print directly using a clean, modern printable CSS overlay hook
  const triggerPrint = () => {
    window.print();
  };

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-sm animate-fade-in" id="memora-print-report">
      <div className="w-full max-w-2xl bg-white border border-slate-200 rounded-2xl shadow-xl overflow-hidden flex flex-col max-h-[90vh] text-left">
        {/* Header - No Print */}
        <div className="p-4 bg-slate-50 border-b border-slate-200 flex items-center justify-between no-print">
          <div className="flex items-center gap-2">
            <FileText size={18} className="text-blue-600" />
            <h2 className="text-sm font-bold text-slate-800">Daily Performance & Timeline Report</h2>
          </div>
          <button 
            onClick={onClose}
            className="p-1.5 rounded-lg text-slate-400 hover:bg-slate-200 hover:text-slate-800 transition-colors"
          >
            <X size={16} />
          </button>
        </div>

        {/* Scrollable Printable Report Preview */}
        <div className="flex-1 overflow-y-auto p-6 md:p-8 space-y-6 print:overflow-visible print:p-0">
          {/* Header Block */}
          <div className="flex flex-col md:flex-row md:items-start justify-between gap-4 border-b border-slate-200 pb-5">
            <div>
              <div className="flex items-center gap-2">
                <span className="w-2 h-2 rounded-full bg-blue-600" />
                <h1 className="text-xl font-extrabold text-slate-900 tracking-tight">Memora AI Workspace</h1>
              </div>
              <p className="text-xs text-slate-500 font-medium mt-0.5">Daily Timeline & Accomplished Milestones</p>
              <p className="text-[11px] text-slate-400 font-mono mt-2 flex items-center gap-1.5">
                <Calendar size={11} /> {dateStr}
              </p>
            </div>
            
            <div className={`px-3 py-2 rounded-xl border flex flex-col items-center md:items-end ${insight.color}`}>
              <span className="text-[9px] font-mono font-bold uppercase tracking-wider">Performance Grade</span>
              <span className="text-sm font-bold tracking-tight">{insight.score}</span>
              <span className="text-[9px] font-medium mt-0.5">{insight.badge}</span>
            </div>
          </div>

          {/* AI Strategy Insights */}
          <div className="bg-slate-50 border border-slate-200 rounded-xl p-4 space-y-1.5">
            <span className="text-[10px] font-bold text-slate-500 uppercase tracking-wider flex items-center gap-1">
              <Sparkles size={12} className="text-blue-600" /> Strategy Performance Note
            </span>
            <p className="text-xs text-slate-700 font-medium italic leading-relaxed">
              "{insight.summary}"
            </p>
          </div>

          {/* Daily Summary Statistics */}
          <div className="grid grid-cols-3 gap-3">
            <div className="bg-white p-3.5 rounded-xl border border-slate-150 text-center flex flex-col justify-between shadow-sm">
              <span className="text-[10px] font-bold text-slate-500 uppercase tracking-wider">Completion Rate</span>
              <span className="text-lg font-bold text-emerald-600 mt-1">{completionPercentage}%</span>
              <span className="text-[9px] text-slate-400 font-mono">({completedCount} / {totalCount} Goals)</span>
            </div>
            <div className="bg-white p-3.5 rounded-xl border border-slate-150 text-center flex flex-col justify-between shadow-sm">
              <span className="text-[10px] font-bold text-slate-500 uppercase tracking-wider">Focus Energy</span>
              <span className="text-lg font-bold text-blue-600 mt-1">{completedDuration}m</span>
              <span className="text-[9px] text-slate-400 font-mono">of {totalDuration}m total</span>
            </div>
            <div className="bg-white p-3.5 rounded-xl border border-slate-150 text-center flex flex-col justify-between shadow-sm">
              <span className="text-[10px] font-bold text-slate-500 uppercase tracking-wider">High Priorities</span>
              <span className="text-lg font-bold text-rose-600 mt-1">{completedHighPriority.length}/{highPriorityTasks.length}</span>
              <span className="text-[9px] text-slate-400 font-mono">milestones completed</span>
            </div>
          </div>

          {/* Completed Milestones List */}
          <div className="space-y-3">
            <h3 className="text-xs font-bold text-slate-400 uppercase tracking-wider flex items-center gap-1.5 pb-1.5 border-b border-slate-100">
              <CheckCircle size={13} className="text-emerald-600" /> Completed Milestones
            </h3>
            {completedTasks.length === 0 ? (
              <p className="text-xs text-slate-450 italic pl-1">No completed tasks or milestones registered for today yet.</p>
            ) : (
              <div className="space-y-3">
                {completedTasks.map((t) => (
                  <div key={t.id} className="border-l-2 border-emerald-500 pl-4 py-0.5 space-y-1">
                    <div className="flex items-start justify-between gap-3">
                      <h4 className="text-xs font-bold text-slate-800 flex items-center gap-1.5">
                        <Check size={11} className="text-emerald-600 flex-shrink-0" />
                        {t.title}
                      </h4>
                      <span className="text-[9px] font-mono text-slate-400 bg-slate-100 border border-slate-200 px-1.5 py-0.5 rounded flex-shrink-0">
                        {t.category}
                      </span>
                    </div>
                    {t.description && (
                      <p className="text-[11px] text-slate-550 leading-relaxed">{t.description}</p>
                    )}
                    <div className="flex items-center gap-3 text-[10px] text-slate-450 font-mono">
                      <span className="flex items-center gap-0.5">
                        <Clock size={10} /> {t.start} - {t.end}
                      </span>
                      <span>•</span>
                      <span>Realized focus: {t.predictedTimeMinutes || t.duration} mins</span>
                    </div>

                    {t.subtasks && t.subtasks.length > 0 && (
                      <div className="pl-3.5 pt-1 space-y-0.5">
                        {t.subtasks.map((s) => (
                          <div key={s.id} className="text-[10px] flex items-center gap-1.5 text-slate-600">
                            <span className="text-emerald-500 font-bold">✓</span>
                            <span className={s.completed ? "line-through text-slate-400" : ""}>{s.text}</span>
                          </div>
                        ))}
                      </div>
                    )}
                  </div>
                ))}
              </div>
            )}
          </div>

          {/* Upcoming Milestones List */}
          <div className="space-y-3">
            <h3 className="text-xs font-bold text-slate-400 uppercase tracking-wider flex items-center gap-1.5 pb-1.5 border-b border-slate-100">
              <Clock size={13} className="text-blue-600" /> Upcoming & Remaining Timeline
            </h3>
            {pendingTasks.length === 0 ? (
              <p className="text-xs text-emerald-600 font-semibold italic pl-1 flex items-center gap-1">
                🎉 Perfect alignment! All scheduled daily focus milestones completed.
              </p>
            ) : (
              <div className="space-y-3">
                {pendingTasks.map((t) => (
                  <div 
                    key={t.id} 
                    className={`border-l-2 pl-4 py-0.5 space-y-1 ${
                      t.priority === "high" ? "border-rose-500 bg-rose-50/10" : "border-slate-300"
                    }`}
                  >
                    <div className="flex items-start justify-between gap-3">
                      <h4 className="text-xs font-bold text-slate-800 flex items-center gap-1.5">
                        {t.title}
                        {t.priority === "high" && (
                          <span className="text-[8px] uppercase tracking-wider font-extrabold bg-rose-100 text-rose-700 px-1 rounded animate-pulse">
                            High Priority
                          </span>
                        )}
                      </h4>
                      <span className="text-[9px] font-mono text-slate-450 bg-slate-100 border border-slate-200 px-1.5 py-0.5 rounded flex-shrink-0">
                        {t.category}
                      </span>
                    </div>
                    {t.description && (
                      <p className="text-[11px] text-slate-550 leading-relaxed">{t.description}</p>
                    )}
                    <div className="flex items-center gap-3 text-[10px] text-slate-450 font-mono">
                      <span className="flex items-center gap-0.5">
                        <Clock size={10} /> {t.start} - {t.end}
                      </span>
                      <span>•</span>
                      <span>Focus block: {t.predictedTimeMinutes || t.duration} mins</span>
                    </div>

                    {t.subtasks && t.subtasks.length > 0 && (
                      <div className="pl-3.5 pt-1 space-y-0.5">
                        {t.subtasks.map((s) => (
                          <div key={s.id} className="text-[10px] flex items-center gap-1.5 text-slate-600">
                            <span className="text-slate-350">•</span>
                            <span>{s.text}</span>
                          </div>
                        ))}
                      </div>
                    )}
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>

        {/* Action Tray - No Print */}
        <div className="p-4 bg-slate-50 border-t border-slate-200 flex flex-col sm:flex-row items-center justify-between gap-3 no-print">
          <div className="flex items-center gap-2">
            <span className="text-[10px] text-slate-400 font-mono">Save to local disk:</span>
            <button
              onClick={downloadMarkdown}
              className="px-3 py-1.5 bg-slate-200 hover:bg-slate-300 text-slate-700 rounded-lg text-xs font-semibold transition flex items-center gap-1"
            >
              <Download size={12} />
              Markdown (.md)
            </button>
            <button
              onClick={downloadHTML}
              className="px-3 py-1.5 bg-indigo-50 hover:bg-indigo-100 text-indigo-700 border border-indigo-200 rounded-lg text-xs font-semibold transition flex items-center gap-1"
            >
              <Download size={12} />
              Styled HTML (.html)
            </button>
          </div>

          <div className="flex items-center gap-2 w-full sm:w-auto justify-end">
            <button
              onClick={onClose}
              className="px-3.5 py-2 bg-white border border-slate-200 hover:bg-slate-100 text-slate-700 rounded-xl text-xs font-medium transition"
            >
              Close Preview
            </button>
            <button
              onClick={triggerPrint}
              className="px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-xl text-xs font-bold shadow-sm transition flex items-center gap-1.5"
            >
              <Printer size={13} />
              Print Report
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
